name: GitHubAction-Basic-Syntax
on : workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First-Job
        run: echo "This is a FIrstJob"
      - name: Second-Job
        run : echo "This is a FirstJob Second Step"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Second-Job
        run: echo "This is Second Job"
      - name: Exiting
        run: echo "Exiting the Repo"
