name: First-Job
on: workflow_dispatch
jobs:
  FirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: First-Job
        run : echo "Hello"
      - name: Second-Job
        run : echo "World"
        
