name: First-File
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome User
        run : echo "Hello Murali, Welcome to GITHUB Actions, Practise Repo"
      - name: Purpose of this Repo
        run : echo "In this Repo, We can learn GitHub Actions by practising it in Real time"
        
